Repository Pawty-Trainer/pawty-trainer-api, pull requests merged in 2021-08, with the labels that each got.

#26 Install Cors
  Gemfile
  Gemfile.lock
  config/initializers/cors.rb
Labels: Backend, core

#38 One tests
  spec/graphql/queries/dogs/dog_spec.rb
  spec/graphql/queries/events/event_spec.rb
  spec/graphql/queries/users/user_spec.rb
Labels: Backend, core

#40 Mutations testing
  spec/graphql/mutations/dogs/create_dog_spec.rb
  spec/graphql/mutations/events/create_event_spec.rb
  spec/graphql/mutations/users/create_user_spec.rb
Labels: documentation, Backend

#43 Mutations update testing
  app/graphql/mutations/update_dog.rb
  spec/graphql/mutations/dogs/destroy_dog_spec.rb
  spec/graphql/mutations/dogs/update_dog_spec.rb
  spec/graphql/mutations/events/update_event_spec.rb
Labels: Backend

#47 Event dog data
  app/graphql/types/dog_type.rb
  app/graphql/types/event_type.rb
  spec/graphql/mutations/dogs/create_dog_spec.rb
  spec/graphql/mutations/dogs/update_dog_spec.rb
  spec/graphql/mutations/events/create_event_spec.rb
  spec/graphql/mutations/events/update_event_spec.rb
  spec/graphql/queries/dogs/dog_spec.rb
  spec/graphql/queries/dogs/dogs_spec.rb
  spec/graphql/queries/events/event_spec.rb
  spec/graphql/queries/events/events_spec.rb
Labels: documentation, enhancement, Backend, endpoint

#48 add back ids to dog and user
  app/graphql/types/dog_type.rb
  app/graphql/types/event_type.rb
  spec/graphql/mutations/events/create_event_spec.rb
  spec/graphql/mutations/events/update_event_spec.rb
  spec/graphql/queries/dogs/dog_spec.rb
  spec/graphql/queries/dogs/dogs_spec.rb
  spec/graphql/queries/events/event_spec.rb
  spec/graphql/queries/events/events_spec.rb
Labels: bug, documentation, enhancement, Backend
